# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.node import Node


class TestNode(unittest.TestCase):
    """ Node unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNode(self):
        """
        Test Node
        """
        model = swagger_client.models.node.Node()


if __name__ == '__main__':
    unittest.main()
