# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.allowed_value import AllowedValue


class TestAllowedValue(unittest.TestCase):
    """ AllowedValue unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllowedValue(self):
        """
        Test AllowedValue
        """
        model = swagger_client.models.allowed_value.AllowedValue()


if __name__ == '__main__':
    unittest.main()
