# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.veritas_information_classifier_vic_api import VeritasInformationClassifierVICApi


class TestVeritasInformationClassifierVICApi(unittest.TestCase):
    """ VeritasInformationClassifierVICApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.veritas_information_classifier_vic_api.VeritasInformationClassifierVICApi()

    def tearDown(self):
        pass

    def test_create_or_update_tag(self):
        """
        Test case for create_or_update_tag

        Create or update tag
        """
        pass

    def test_create_pattern(self):
        """
        Test case for create_pattern

        Create pattern
        """
        pass

    def test_create_policy(self):
        """
        Test case for create_policy

        Create policy
        """
        pass

    def test_delete_pattern(self):
        """
        Test case for delete_pattern

        Delete pattern
        """
        pass

    def test_delete_policy(self):
        """
        Test case for delete_policy

        Delete policy
        """
        pass

    def test_delete_tag(self):
        """
        Test case for delete_tag

        Delete tag
        """
        pass

    def test_get_metadata_definitions(self):
        """
        Test case for get_metadata_definitions

        List metadata definitions
        """
        pass

    def test_get_pattern(self):
        """
        Test case for get_pattern

        Get pattern
        """
        pass

    def test_get_pattern_collection(self):
        """
        Test case for get_pattern_collection

        List patterns
        """
        pass

    def test_get_policies_by_pattern(self):
        """
        Test case for get_policies_by_pattern

        List policies that use a pattern
        """
        pass

    def test_get_policies_by_tag(self):
        """
        Test case for get_policies_by_tag

        List policies that use a tag
        """
        pass

    def test_get_policy(self):
        """
        Test case for get_policy

        Get policy
        """
        pass

    def test_get_policy_collection(self):
        """
        Test case for get_policy_collection

        List policies
        """
        pass

    def test_get_tag(self):
        """
        Test case for get_tag

        Get tag
        """
        pass

    def test_get_tag_property_definitions(self):
        """
        Test case for get_tag_property_definitions

        List tag property definitions
        """
        pass

    def test_get_tags_collection(self):
        """
        Test case for get_tags_collection

        List tags
        """
        pass

    def test_patch_policy(self):
        """
        Test case for patch_policy

        Patch policy
        """
        pass

    def test_reset_policy(self):
        """
        Test case for reset_policy

        Reset policy to defaults
        """
        pass

    def test_update_pattern(self):
        """
        Test case for update_pattern

        Update pattern
        """
        pass

    def test_update_policy(self):
        """
        Test case for update_policy

        Update policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
