# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .allowed_value import AllowedValue
from .error_response import ErrorResponse
from .json_patch_document import JsonPatchDocument
from .link import Link
from .metadata_definition import MetadataDefinition
from .metadata_definition_collection import MetadataDefinitionCollection
from .node import Node
from .operator_node import OperatorNode
from .pattern import Pattern
from .pattern_collection import PatternCollection
from .policy import Policy
from .policy_body import PolicyBody
from .policy_collection import PolicyCollection
from .tag import Tag
from .tag_property import TagProperty
from .tag_property_allowed_value import TagPropertyAllowedValue
from .tag_property_definition import TagPropertyDefinition
from .tag_property_definition_collection import TagPropertyDefinitionCollection
from .tags_collection import TagsCollection
