# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MetadataDefinition(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, display_name=None, type=None, allowed_values=None, aliases=None):
        """
        MetadataDefinition - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'display_name': 'str',
            'type': 'str',
            'allowed_values': 'list[AllowedValue]',
            'aliases': 'list[str]'
        }

        self.attribute_map = {
            'name': 'name',
            'display_name': 'displayName',
            'type': 'type',
            'allowed_values': 'allowedValues',
            'aliases': 'aliases'
        }

        self._name = name
        self._display_name = display_name
        self._type = type
        self._allowed_values = allowed_values
        self._aliases = aliases

    @property
    def name(self):
        """
        Gets the name of this MetadataDefinition.

        :return: The name of this MetadataDefinition.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this MetadataDefinition.

        :param name: The name of this MetadataDefinition.
        :type: str
        """

        self._name = name

    @property
    def display_name(self):
        """
        Gets the display_name of this MetadataDefinition.

        :return: The display_name of this MetadataDefinition.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """
        Sets the display_name of this MetadataDefinition.

        :param display_name: The display_name of this MetadataDefinition.
        :type: str
        """

        self._display_name = display_name

    @property
    def type(self):
        """
        Gets the type of this MetadataDefinition.

        :return: The type of this MetadataDefinition.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this MetadataDefinition.

        :param type: The type of this MetadataDefinition.
        :type: str
        """
        allowed_values = ["String", "Number", "DateTime"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def allowed_values(self):
        """
        Gets the allowed_values of this MetadataDefinition.

        :return: The allowed_values of this MetadataDefinition.
        :rtype: list[AllowedValue]
        """
        return self._allowed_values

    @allowed_values.setter
    def allowed_values(self, allowed_values):
        """
        Sets the allowed_values of this MetadataDefinition.

        :param allowed_values: The allowed_values of this MetadataDefinition.
        :type: list[AllowedValue]
        """

        self._allowed_values = allowed_values

    @property
    def aliases(self):
        """
        Gets the aliases of this MetadataDefinition.

        :return: The aliases of this MetadataDefinition.
        :rtype: list[str]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """
        Sets the aliases of this MetadataDefinition.

        :param aliases: The aliases of this MetadataDefinition.
        :type: list[str]
        """

        self._aliases = aliases

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MetadataDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
