# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PolicyBody(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, conditions_tree=None):
        """
        PolicyBody - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'conditions_tree': 'OperatorNode'
        }

        self.attribute_map = {
            'conditions_tree': 'conditionsTree'
        }

        self._conditions_tree = conditions_tree

    @property
    def conditions_tree(self):
        """
        Gets the conditions_tree of this PolicyBody.
        A tree of conditions that form the structure of the policy.  Leaf nodes are always conditions.  Non-leaf nodes are always operators that can be used to combine the conditions.

        :return: The conditions_tree of this PolicyBody.
        :rtype: OperatorNode
        """
        return self._conditions_tree

    @conditions_tree.setter
    def conditions_tree(self, conditions_tree):
        """
        Sets the conditions_tree of this PolicyBody.
        A tree of conditions that form the structure of the policy.  Leaf nodes are always conditions.  Non-leaf nodes are always operators that can be used to combine the conditions.

        :param conditions_tree: The conditions_tree of this PolicyBody.
        :type: OperatorNode
        """

        self._conditions_tree = conditions_tree

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PolicyBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
