# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TagPropertyDefinition(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, values=None, default_value=None):
        """
        TagPropertyDefinition - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'values': 'list[TagPropertyAllowedValue]',
            'default_value': 'str'
        }

        self.attribute_map = {
            'name': 'name',
            'values': 'values',
            'default_value': 'defaultValue'
        }

        self._name = name
        self._values = values
        self._default_value = default_value

    @property
    def name(self):
        """
        Gets the name of this TagPropertyDefinition.
        Name of a property, for example indexProperty or retentionCategory.

        :return: The name of this TagPropertyDefinition.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this TagPropertyDefinition.
        Name of a property, for example indexProperty or retentionCategory.

        :param name: The name of this TagPropertyDefinition.
        :type: str
        """

        self._name = name

    @property
    def values(self):
        """
        Gets the values of this TagPropertyDefinition.
        Allowed values for a property.  For example indexProperty may have allowed values evtag.category, evtag.inclusion etc.

        :return: The values of this TagPropertyDefinition.
        :rtype: list[TagPropertyAllowedValue]
        """
        return self._values

    @values.setter
    def values(self, values):
        """
        Sets the values of this TagPropertyDefinition.
        Allowed values for a property.  For example indexProperty may have allowed values evtag.category, evtag.inclusion etc.

        :param values: The values of this TagPropertyDefinition.
        :type: list[TagPropertyAllowedValue]
        """

        self._values = values

    @property
    def default_value(self):
        """
        Gets the default_value of this TagPropertyDefinition.
        Optional default value for a property.  If not specified, the property's default value is null / undefined.

        :return: The default_value of this TagPropertyDefinition.
        :rtype: str
        """
        return self._default_value

    @default_value.setter
    def default_value(self, default_value):
        """
        Sets the default_value of this TagPropertyDefinition.
        Optional default value for a property.  If not specified, the property's default value is null / undefined.

        :param default_value: The default_value of this TagPropertyDefinition.
        :type: str
        """

        self._default_value = default_value

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TagPropertyDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
