# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TagPropertyAllowedValue(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, value=None, display_name=None, flags=None):
        """
        TagPropertyAllowedValue - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'value': 'str',
            'display_name': 'str',
            'flags': 'list[str]'
        }

        self.attribute_map = {
            'value': 'value',
            'display_name': 'displayName',
            'flags': 'flags'
        }

        self._value = value
        self._display_name = display_name
        self._flags = flags

    @property
    def value(self):
        """
        Gets the value of this TagPropertyAllowedValue.

        :return: The value of this TagPropertyAllowedValue.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this TagPropertyAllowedValue.

        :param value: The value of this TagPropertyAllowedValue.
        :type: str
        """

        self._value = value

    @property
    def display_name(self):
        """
        Gets the display_name of this TagPropertyAllowedValue.

        :return: The display_name of this TagPropertyAllowedValue.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """
        Sets the display_name of this TagPropertyAllowedValue.

        :param display_name: The display_name of this TagPropertyAllowedValue.
        :type: str
        """

        self._display_name = display_name

    @property
    def flags(self):
        """
        Gets the flags of this TagPropertyAllowedValue.

        :return: The flags of this TagPropertyAllowedValue.
        :rtype: list[str]
        """
        return self._flags

    @flags.setter
    def flags(self, flags):
        """
        Sets the flags of this TagPropertyAllowedValue.

        :param flags: The flags of this TagPropertyAllowedValue.
        :type: list[str]
        """

        self._flags = flags

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TagPropertyAllowedValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
